# RAG Pipeline for Product Recommendation

## Goal
Build a complete RAG logic that retrieves relevant products (by text or image) and then uses a generative LLM to answer user questions based on those products.

## Inputs
- `project_data_clean.parquet`: Main dataframe
- `text_search.index`: FAISS index for text
- `image_search.index`: FAISS index for images
- `image_ids.npy`: Mapping image index to product codes

In [1]:
import pandas as pd
import numpy as np
import faiss
import torch
from PIL import Image
from transformers import AutoTokenizer, AutoModel, ViTImageProcessor, ViTModel, AutoModelForCausalLM
import os

## 1. Load Data & Indices

In [3]:
# Load Dataframe
DATA_PATH = "project_data_clean.parquet"
df = pd.read_parquet(DATA_PATH)
print(f"Loaded Dataframe: {df.shape}")

# Load Image IDs mapping
image_ids = np.load('../models/image_ids.npy', allow_pickle=True)
print(f"Loaded Image IDs: {image_ids.shape}")

# Load FAISS Indices
text_index = faiss.read_index('../models/text_search.index')
image_index = faiss.read_index('../models/image_search.index')
print(f"Loaded Text Index: {text_index.ntotal} vectors")
print(f"Loaded Image Index: {image_index.ntotal} vectors")

Loaded Dataframe: (76935, 11)
Loaded Image IDs: (76866,)
Loaded Text Index: 76935 vectors
Loaded Image Index: 76866 vectors

## 2. Load Models

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# 1. Text Embedding Model (MiniLM)
text_model_name = 'sentence-transformers/all-MiniLM-L6-v2'
tokenizer = AutoTokenizer.from_pretrained(text_model_name)
text_model = AutoModel.from_pretrained(text_model_name).to(device)

# 2. Image Embedding Model (ViT)
vit_model_name = 'google/vit-base-patch16-224-in21k'
vit_processor = ViTImageProcessor.from_pretrained(vit_model_name)
vit_model = ViTModel.from_pretrained(vit_model_name).to(device)

# 3. Generative LLM (Qwen 2.5)
llm_model_name = 'Qwen/Qwen2.5-1.5B-Instruct'
llm_tokenizer = AutoTokenizer.from_pretrained(llm_model_name)
llm_model = AutoModelForCausalLM.from_pretrained(
    llm_model_name,
    device_map="auto",
    torch_dtype="auto"
)

Using device: cuda

tokenizer_config.json: 0.00B [00:00, ?B/s]

C:\Users\hulkk\Desktop\studia\machine learning project\machine-learning-project\venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\hulkk\.cache\huggingface\hub\models--Qwen--Qwen2.5-1.5B-Instruct. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

'(MaxRetryError('HTTPSConnectionPool(host=\'cas-bridge.xethub.hf.co\', port=443): Max retries exceeded with url: /xet-bridge-us/66e98dd5899bdb384bd953b4/46ea4ba5786759efecf127c64dee654df39a3f02fdeaafc67734a06574619467?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=cas%2F20251130%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20251130T195144Z&X-Amz-Expires=3600&X-Amz-Signature=6c20c73a3ed071e90fd64fad1408fedc7777e30d8b74e219dc59c3c1f761845b&X-Amz-SignedHeaders=host&X-Xet-Cas-Uid=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&x-id=GetObject&Expires=1764535904&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NDUzNTkwNH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2FzLWJyaWRnZS54ZXRodWIuaGYuY28veGV0LWJyaWRnZS11cy82NmU5OGRkNTg5OWJkYjM4NGJkOTUzYjQvNDZlYTRiYTU3ODY3NTllZmVjZjEyN2M2NGRlZTY1NGRmMzlhM2YwMmZkZWFhZmM2NzczNGEwNjU3NDYxOTQ2NyoifV19&Signature=ClyvkiwYvw4l~YWqAjw2DL4J15~DOe5Lk8YhLpewAWoM22SLkQDUYP7vP-cybJKbCb~rloJou0T0234Y~s1yMjIgLbuM2C34gA49PvHlB9l011c5dsrJA9MLS3Npfe~Gn3lulzBRXAjcM7KqzVlq5BYDLzw6RADKj4zZu2ZOx76qMX2RhKF3ZfzL0WkL7emPaUzeGtSf8e1ul~4mCnLJOTLJpTBZF-zNkKVeiDZ6U4jOPcQBlxGa4LZidk3kOWuqNiX0gwxiJFgGdlw7KCZpAvmC2fuRbyvxgV1uAZyBXpg8uG11IGw4~TWwDV8Vd9mD~4CetvaL8V8emNEIQDGVyw__&Key-Pair-Id=K2L8F4GPSG1IFC (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000288D6810260>: Failed to resolve \'cas-bridge.xethub.hf.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 2d7aed49-8108-4058-b50c-6d01e90cb396)')' thrown while requesting GET https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct/resolve/main/model.safetensors

Retrying in 1s [Retry 1/5].

'(MaxRetryError('HTTPSConnectionPool(host=\'cas-bridge.xethub.hf.co\', port=443): Max retries exceeded with url: /xet-bridge-us/66e98dd5899bdb384bd953b4/46ea4ba5786759efecf127c64dee654df39a3f02fdeaafc67734a06574619467?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=cas%2F20251130%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20251130T200554Z&X-Amz-Expires=3600&X-Amz-Signature=eee0e7cf7c4ae24f7b1bd9b82339b6439b90d6f3380802a85c6aa217b789e9f8&X-Amz-SignedHeaders=host&X-Xet-Cas-Uid=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&x-id=GetObject&Expires=1764536754&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NDUzNjc1NH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2FzLWJyaWRnZS54ZXRodWIuaGYuY28veGV0LWJyaWRnZS11cy82NmU5OGRkNTg5OWJkYjM4NGJkOTUzYjQvNDZlYTRiYTU3ODY3NTllZmVjZjEyN2M2NGRlZTY1NGRmMzlhM2YwMmZkZWFhZmM2NzczNGEwNjU3NDYxOTQ2NyoifV19&Signature=boisQSh4nZuzd0GD2tj0Y2GKAWTcXV2O5OGB-dVAptNcDyamvpS3-sazE8EJkvhLrosr4SAx8gRGIWasmZXrU69cPtLJpAoqgwIOOuFCTQ3VdhVNNqDgPD6Q8peUe0xWJI4Hi4s7GMQ~o3zt0DSVVb9JH9DScX3AOYbIr8lYdHbr7RDbjYiygLP24Jp-MFsp3v19fsawRvCXsYkzSH-n9Ilf-oqnPTwMvqcLsy6ygJj3SLSym3hGTCBoFDFbFRo9b7bJlTmKsFdrzJNfm9HQQY~rZNldwJf8NMlz~v8Q5OUbyvhmGuK2EMdP~-tZZkbRtQL~xuBjJrbjUgCQXdDJGQ__&Key-Pair-Id=K2L8F4GPSG1IFC (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000288D6812990>: Failed to resolve \'cas-bridge.xethub.hf.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 1cec6755-b463-4e64-9f15-834fd3705fb1)')' thrown while requesting GET https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct/resolve/main/model.safetensors

Retrying in 2s [Retry 2/5].

'(MaxRetryError('HTTPSConnectionPool(host=\'cas-bridge.xethub.hf.co\', port=443): Max retries exceeded with url: /xet-bridge-us/66e98dd5899bdb384bd953b4/46ea4ba5786759efecf127c64dee654df39a3f02fdeaafc67734a06574619467?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=cas%2F20251130%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20251130T200602Z&X-Amz-Expires=3600&X-Amz-Signature=f0661a256080755b9a5886f1f023743a1a8f5543b81afb709f2362d143d42a91&X-Amz-SignedHeaders=host&X-Xet-Cas-Uid=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&x-id=GetObject&Expires=1764536762&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NDUzNjc2Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2FzLWJyaWRnZS54ZXRodWIuaGYuY28veGV0LWJyaWRnZS11cy82NmU5OGRkNTg5OWJkYjM4NGJkOTUzYjQvNDZlYTRiYTU3ODY3NTllZmVjZjEyN2M2NGRlZTY1NGRmMzlhM2YwMmZkZWFhZmM2NzczNGEwNjU3NDYxOTQ2NyoifV19&Signature=Nzh3-2bMCjMtTmD1LUh~M6getgyZ2iVH0RDhnFyLiWQ3-x7ErO1nDBYpZHeM5rQWBXeAG7jSwgp~GMHH1h~2aAoXKYNk7wtpbq6z2VtLo6ynwsfeVyHNiNc-bj5BnpfsCX1MyCeXb5SRxtS~CKO8BeOqYzWDv8CD-fftKnMHLh8SGKGCbOOYoLVCJHu0lCr4fQgy1q~IYn8nX82mMnyE5dUC1~Wha9tOo2uiPFj18JFohi9Rp3qDkYFs8KT1mbKy0Z42gRkWx1Cy6UTXbEGOs5l~Cm4F9LbC0G98BFBhSvGbBhi7rMKTEaFxcKQdtcI1WE~hzudPOpDwGtFhR-CuLA__&Key-Pair-Id=K2L8F4GPSG1IFC (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000288F25AF590>: Failed to resolve \'cas-bridge.xethub.hf.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 83e8556d-8a15-46af-ae67-663776316f91)')' thrown while requesting GET https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct/resolve/main/model.safetensors

Retrying in 4s [Retry 3/5].

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

## 3. Retrieval Logic (Refactored)

In [ ]:
def get_text_embedding(text):
    inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=128).to(device)
    with torch.no_grad():
        outputs = text_model(**inputs)
    # Mean pooling
    embeddings = outputs.last_hidden_state.mean(dim=1)
    return embeddings.cpu().numpy()

def get_image_embedding(image):
    if isinstance(image, str):
        image = Image.open(image).convert("RGB")
    inputs = vit_processor(images=image, return_tensors="pt").to(device)
    with torch.no_grad():
        outputs = vit_model(**inputs)
    return outputs.last_hidden_state[:, 0, :].cpu().numpy()

def retrieve_products(query, image=None, k=5):
    """
    Retrieves products using Reciprocal Rank Fusion (RRF).
    This ensures that items matching BOTH text and image appear at the top.
    """
    # Dictionaries to hold {index: rrf_score}
    scores = {}
    
    # RRF Constant
    c = 60
    
    # 1. Text Search
    if query:
        query_vector = get_text_embedding(query)
        distances, indices = text_index.search(query_vector, k * 2) # Get more candidates
        text_indices = indices[0].tolist()
        
        for rank, idx in enumerate(text_indices):
            if idx not in scores: scores[idx] = 0
            # 1 / (rank + k) formula
            scores[idx] += 1 / (c + rank + 1)
            
    # 2. Image Search
    if image is not None:
        query_vector = get_image_embedding(image)
        distances, indices = image_index.search(query_vector, k * 2)
        retrieved_img_indices = indices[0]
        
        # Convert FAISS indices to DataFrame indices using image_ids map
        for rank, img_idx in enumerate(retrieved_img_indices):
            if img_idx < len(image_ids):
                code = image_ids[img_idx]
                # Find the dataframe index for this code
                matches = df.index[df['code'] == code].tolist()
                if matches:
                    df_idx = matches[0]
                    if df_idx not in scores: scores[df_idx] = 0
                    scores[df_idx] += 1 / (c + rank + 1)
    
    # 3. Sort by Score (Descending)
    sorted_indices = sorted(scores.keys(), key=lambda x: scores[x], reverse=True)
    
    # 4. Return top K results
    top_indices = sorted_indices[:k]
    results = df.loc[top_indices]
    
    return results

## 4. Generation Logic (Refactored)

In [5]:
def format_product_for_llm(row):
    """
    Cleans product data to remove N/A values and keep the context concise.
    """
    parts = []
    
    # Always include name
    name = row.get('product_name')
    if not name: return ""
    parts.append(f"Name: {name}")
    
    # Only include nutritional info if it exists (is not None/NaN)
    # We round to 1 decimal place for readability
    if pd.notna(row.get('energy-kcal_100g')):
        parts.append(f"Calories: {row['energy-kcal_100g']:.0f}kcal")
        
    if pd.notna(row.get('proteins_100g')):
        parts.append(f"Protein: {row['proteins_100g']:.1f}g")
        
    if pd.notna(row.get('fat_100g')):
        parts.append(f"Fat: {row['fat_100g']:.1f}g")
        
    if pd.notna(row.get('carbs_100g')):
        parts.append(f"Carbs: {row['carbs_100g']:.1f}g")
        
    # Truncate ingredients to save tokens (first 100 chars)
    ingr = str(row.get('ingredients_text', ''))
    if ingr and ingr != 'None' and ingr != 'nan':
        if len(ingr) > 100:
            ingr = ingr[:100] + "..."
        parts.append(f"Ingredients: {ingr}")
        
    return " | ".join(parts)

def generate_answer(user_query, products):
    """
    Generates an answer using Qwen 2.5 with Chat Template.
    """
    if products.empty:
        return "I couldn't find any relevant products."

    # 1. Build a clean, dense context string
    product_contexts = []
    for i, (_, row) in enumerate(products.iterrows()):
        clean_info = format_product_for_llm(row)
        if clean_info:
            product_contexts.append(f"Product {i+1}: {clean_info}")
    
    context_str = "\n".join(product_contexts)
    
    # 2. Build Chat Messages
    messages = [
        {"role": "system", "content": "You are an expert Nutritionist. Analyze the provided product data. Use general knowledge to fill gaps. Be honest about unhealthy items."}, 
        {"role": "user", "content": f"Here is the product data:\n{context_str}\n\nQuestion: {user_query}"}
    ]
    
    # 3. Apply Chat Template
    text = llm_tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    
    # 4. Generate
    model_inputs = llm_tokenizer([text], return_tensors="pt").to(device)
    
    generated_ids = llm_model.generate(
        **model_inputs,
        max_new_tokens=256,
        do_sample=False,
        temperature=0.0
    )
    
    # 5. Decode (remove prompt)
    generated_ids = [ 
        output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]
    
    response = llm_tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    return response

## 5. Test Cases

In [6]:
# Test Case 1: Text Search
query = "Find high protein snacks"
print(f"Query: {query}")
retrieved_products = retrieve_products(query, k=3)
print(f"Retrieved {len(retrieved_products)} products.")
display(retrieved_products[['product_name', 'proteins_100g']])

answer = generate_answer(query, retrieved_products)
print(f"\nAnswer: {answer}")

Query: Find high protein snacks
Retrieved 3 products.

               product_name  proteins_100g
66174  High protein fit 40%      40.000000
34989          Protein Kick      28.000000
71614      High protein bar      41.669998

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Answer: Based on the provided product data, here are some high-protein snack options:

### Product 1: High Protein Fit 40%
- **Protein:** 40.0g
- **Fat:** 17.0g
- **Carbs:** 24.0g

This snack contains a good amount of protein and moderate amounts of fat and carbs. It's made with ingredients like Brennwert/Energy/Energia, which could be considered healthy.

### Product 2: Protein Kick
- **Protein:** 28.0g
- **Fat:** 30.0g
- **Carbs:** 20.0g

This snack also provides a decent amount of protein but has higher levels of fat and carbohydrates compared to the first option. The ingredients list includes germinated seeds, which can be nutritious if prepared properly.

### Product 3: High Protein Bar
- **Protein:** 41.7g
- **Fat:** 11.1g
- **Carbs:** 34.7g

This bar offers a significant amount of protein while having lower levels of fat and carbs compared to the previous two products. However, it uses soy protein isolate

In [7]:
# Test Case 2: Image Search
image_path = "../images/0000111103201.jpg"
if os.path.exists(image_path):
    print(f"\nImage Query: {image_path}")
    retrieved_products_img = retrieve_products("", image=image_path, k=3)
    display(retrieved_products_img[['product_name']])
    answer_img = generate_answer("Describe these products", retrieved_products_img)
    print(f"Answer: {answer_img}")
else:
    print(f"Image not found: {image_path}")

Image Query: ../images/0000111103201.jpg

                product_name
69574                Isalean
48721  Vegan Protein Vanilla
6934               Spiruline

Answer: Product 1: Isalean is a high-protein supplement that contains whey protein concentrate and other ingredients like isomaltooligosaccharides and skim milk powder. It has a moderate amount of fat at 11.9 grams per serving and a higher carb content at 35.6 grams.

Product 2: Vegan Protein Vanilla is a vegan protein supplement with a higher protein content than Isalean at 62.5 grams per serving. It also includes pea protein isolate, organic brown rice protein concentrate, and natural vanilla flavoring. The fat content is lower compared to Isalean at 9.4 grams per serving, but it still provides some fat from the added ingredients.

Product 3: Spiruline is a nutritional supplement made primarily from spirulina, which is a type of blue-green algae. It offers a significant amount of protein at 63.0 grams per serving, along with a relatively low-fat content of only 5.5 grams. The carbs in this product come mainly from the spirulina itself, making it a good source of plant-based carbohydrates.

In [8]:
# Test Case 3: Hybrid Search (Text + Image)
image_path = "../images/0000111103201.jpg"
query = "healthy snack"
if os.path.exists(image_path):
    print(f"\nHybrid Query: '{query}' + Image")
    retrieved_products_hybrid = retrieve_products(query, image=image_path, k=3)
    print(f"Retrieved {len(retrieved_products_hybrid)} products.")
    display(retrieved_products_hybrid[['product_name']])
    
    answer_hybrid = generate_answer("Which of these is the best choice for a low-calorie diet, and why?", retrieved_products_hybrid)
    print(f"Answer: {answer_hybrid}")

Hybrid Query: 'healthy snack' + Image
Retrieved 3 products.

           product_name
52278      Banana Chips
69574           Isalean
63269  Wholesome Medley

Answer: Based on the nutritional information provided, Product 3, "Wholesome Medley," appears to be the best choice for someone following a low-calorie diet due to its lower calorie content compared to the other two products.

**Product 1: Banana Chips**
- **Protein:** 3.3g
- **Fat:** 30.0g
- **Carbs:** 63.3g

This product contains significantly more fat and carbohydrates than the others, which can contribute to higher caloric intake. The high-fat content in banana chips often comes from added oils like coconut oil, which adds calories without providing substantial nutrition.

**Product 2: Isalean**
- **Protein:** 40.7g
- **Fat:** 11.9g
- **Carbs:** 35.6g

Isalean has a relatively high amount of protein but also includes significant amounts of both fat and carbs. While it's not as calorically dense as the first option, it still provides a moderate level of nutrients that could be beneficial if consumed in moderation.

**Product 3: Wholesome Medley**
- **Protein:** 10.7g
- **Fat:** 3